### ISSUE TITLE
add_mod.py and friends shouldn't make asumptions about where they're run from

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/DreamAssemblerXXL#14]
```
bombcar@lappy386 ~/Documents/GitHub/DreamAssemblerXXL (master*) $ src/gtnh/add_mod.py Catwalks-2
Trying to add Catwalks-2
Traceback (most recent call last):
  File "/Users/bombcar/Documents/GitHub/DreamAssemblerXXL/src/gtnh/add_mod.py", line 68, in <module>
    add_mod()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/bombcar/Documents/GitHub/DreamAssemblerXXL/src/gtnh/add_mod.py", line 30, in add_mod
    new_mod = new_mod_from_repo(new_repo)
  File "/Users/bombcar/Documents/GitHub/DreamAssemblerXXL/src/gtnh/add_mod.py", line 48, in new_mod_from_repo
    license = get_license(repo)
  File "/Users/bombcar/Documents/GitHub/DreamAssemblerXXL/src/gtnh/utils.py", line 65, in get_license
    with open("../../licenses_from_boubou.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../licenses_from_boubou.json'
```

It should do that equivalent of bash `$dirname($(realpath "$0"))`

**Comment by mitchej123** [comment]
whoops.  Swap it out with how I did it in load_gtnh_modpack
